export const sideBarSx = {
  bodySidebar: {
    width: "250px",
  },
  containerSidebar: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: "25px",
  },
  contain: {
    // height: "100vh",
  },
  bannerSidebar: {
    width: "227px",
    height: "265px",
    backgroundColor: "#5D5FEF",
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
    justifyContent: "space-between",
    paddingLeft: "20px",
    borderRadius: "10px",
    position: "relative",
    overflow: "hidden",
  },
  circle1: {
    width: "323px",
    height: "323px",
    border: "1px solid #A5A6F6",
    borderRadius: "50%",
    position: "absolute",
    bottom: "-160px",
    right: "-160px",
  },
  circle2: {
    width: "323px",
    height: "323px",
    border: "1px solid #FFFFFF",
    backgroundColor: "#7879F1",
    borderRadius: "50%",
    position: "absolute",
    bottom: "-198px",
    right: "-198px",
  },
  circle3: {
    width: "323px",
    height: "323px",
    border: "1px solid #FFFFFF",
    backgroundColor: "#A5A6F6",
    borderRadius: "50%",
    position: "absolute",
    bottom: "-230px",
    right: "-230px",
  },

  textAnalytics: {
    width: "149px",
    display: "flex",
    textAlign: "start",
    color: "white",
    marginTop: "16px",
  },
  analytic: {
    fontSize: "18px",
    fontWeight: "600",
  },
  buttonAnalytic: {
    marginBottom: "20px",
  },
  buttonSidebar: {
    width: "119px",
    height: "45px",
    borderRadius: "10px",
    boder: "noner",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    fontSize: "12px",
    color: "white",
    fontWeight: " 600",
    fontSize: "12px",
  },
  menuSidebar: {
    textAlign: "start",
    width: "227px",
    backgroundColor: "#fafafa",
    borderRadius: "10px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    height: "100%",
  },
  menuTextSidebar: {
    display: "flex",
    flexDirection: "column",
    gap: "28px",
    paddingTop: "20px",
    paddingLeft: "20px",
  },
  sideTitle: {
    display: "flex",
    gap: "12px",
    flexDirection: "column",
  },
  textSide: {
    display: "flex",
    flexDirection: "column",
    gap: "5px",
  },
  topMenu: {
    fontSize: "24px",
    fontWeight: "500",
  },
  thisWeek: {
    fontSize: "24px",
    fontWeight: "500",
    color: "#f17300",
  },
  dateSide: {
    fontSize: "14px",
    color: "#98949e",
  },

  firstSpesialMenu: {
    width: "195px",
    height: "62px",
    background: "#ffffff",
    boxShadow: "4px 4px 10px rgba(0, 0, 0, 0.05)",
    borderRadius: "8px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    position: "relative",
  },
  no1: {
    background: "#F17300",
    boxShadow: "2px 2px 0px #464646",
    transform: "rotate(8deg)",
    position: "absolute",
    width: " 23.81px",
    height: "23.44px",
    display: "flex",
    justifyContent: "center",
    textAlign: "center",
    fontWeight: "700",
    fontSize: "14px",
    color: "white",
    right: "3px",
    top: "-8px",
  },
  titleFirst: {
    fontWeight: " 700",
    fontsize: "14px",
    textAlign: "start",
    marginLeft: "10px",
    color: "black",
  },
  spesial: {
    fontWeight: " 700",
    fontsize: "15px",
    textAlign: "start",
    marginLeft: "10px",
    color: "black",
  },
  sideSpesialMenu: {
    // marginLeft: "10px",
    color: " #98949e",
    display: " flex",
    flexDirection: "column",
    gap: "24px",
    fontWeight: "600",
    fontSize: "12px",
    height: "100%",
  },
  sideSpesialMenuMenu: {
    display: "flex",
    gap: "30px",
    justifyContent: "space-around",
    flexDirection: "column",
  },
  iconGrafik: {
    // height: "100%",
    // backgroundColor: "red",
    // marginLeft: "-20px",
  },
};
