export const tableSx = {
  tableContainer: {
    boxShadow: "none !important",
    marginTop: "20px",
  },
  borderNone: {
    borderBottom: "none !important",
  },
  spaceBw: {
    display: "flex",
    justifyContent: "space-between",
  },
  centerText: {
    display: "flex",
    justifyContent: "center",
  },
  tableRow: {
    fontSize: "14px",
    fontWeight: "600",
    borderBottom: "none !important",
  },
  warga: {
    width: "93px",
    height: "37px",
    bgcolor: "#FEFBF6",
    color: "#F46B45",
    borderRadius: "4px",
    fontSize: "14px",
    fontWeight: "600",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  sultan: {
    width: "104px",
    height: "37px",
    bgcolor: "#F6FCFE",
    color: "#11998E",
    borderRadius: "4px",
    fontSize: "14px",
    fontWeight: "600",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  juragan: {
    width: "93px",
    height: "37px",
    bgcolor: "#F6FCFE",
    color: "#2F80ED",
    borderRadius: "4px",
    fontSize: "14px",
    fontWeight: "600",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  konglomerat: {
    width: "135px",
    height: "37px",
    bgcolor: " #FEF5FF",
    color: "#7F00FF",
    borderRadius: "4px",
    fontSize: "14px",
    fontWeight: "600",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  btnDetail: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "89.8px",
    height: "29px",
    color: "black",
    bgcolor: "#FAFAFA",
    gap: "8px",
  },
  btnEdit: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "30px",
    height: "29px",
    color: "black",
    bgcolor: "#FAFAFA",
  },
  btnDlt: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "30px",
    height: "29px",
    color: "black",
    bgcolor: "#FEF5F6",
  },
};
