export const bannerSx = {
  containerBanner: {
    bgcolor: "#5D5FEF",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-around",
    // gap: "20px",
    height: " 167px",
    padding: "20px",
    borderRadius: "8px",
    backgroundImage:
      "url('../../../image/iconBanner/unsplash_wtevVfGYwnM.png')",
    backgroundRepeat: "no-repeat",
    backgroundSize: "60%",
    backgroundPositionX: "right",
  },
  customerText: {
    fontSize: "20px",
    fontWeight: "700",
    color: "#fff",
  },
  textBAnner: {
    fontSize: "12px",
    width: "341px",
    height: "48px",
    color: "#fff",
  },
  conatinerButton: {
    display: "flex",
    justifyContent: "space-evenly",
    gap: "20px",
  },
  ButtonNewCs: {
    color: "#fff",
    fontSize: "14px",
    fontWeight: "600",
    background: "rgba(255, 255, 255, 0.2)",
    borderRadius: "8px",
    width: " 200px",
    height: " 45px",
    display: "flex",
    gap: "12px",
  },
  BtnFilter: {
    color: "#fff",
    fontSize: "14px",
    fontWeight: "600",
    background: "rgba(255, 255, 255, 0.2)",
    borderRadius: "8px",
    width: " 120px",
    height: "45px",
    display: "flex",
    gap: "12px",
  },
  btnRefresh: {
    color: "#fff",
    fontSize: "14px",
    fontWeight: "600",
    background: "rgba(255, 255, 255, 0.2)",
    borderRadius: "8px",
    width: " 120px",
    height: " 45px",
    display: "flex",
    gap: "12px",
  },
  btnPrint: {
    color: "#fff",
    fontSize: "14px",
    fontWeight: "600",
    background: "rgba(255, 255, 255, 0.2)",
    borderRadius: "8px",
    width: " 48px",
    height: " 45px",
  },
};
